channels:
- conda-forge
dependencies:
- python=3.14.0
- pip<=25.3
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - dill==0.4.0
  - numpy==2.3.5
  - pandas==2.3.3
  - pydot==4.0.1
  - torch==2.9.1
  - torchvision==0.24.1
  - tqdm==4.67.1
name: mlflow-env
